basic_settings:
  site_title: Lizhen Portfolio
  favicon_image: https://res.cloudinary.com/dxzphanl0/image/upload/v1553664755/favicon.icon.png

header_settings:
  logo_image: https://res.cloudinary.com/dxzphanl0/image/upload/v1559701016/logo.png
  logo_width: 180

menu_settings:
  menu_items:
    - title: 'ID'
      url: '/'
    - title: 'UX & Web'
      url: '/graphic'
    - title: 'Graphic'
      url: '/illustration'
    - title: 'About'
      url: '/about'


footer_settings:
  logo_image: https://res.cloudinary.com/dxzphanl0/image/upload/v1559701016/logo.png
  logo_width: 70
  footer_tagline:

grid_settings:
  overlay_opacity: 0.8
  grid_spacing: 10

contact_settings:
  form_action: 'https://formspree.io/your@email.com'
  confirmation_url: '/thanks'
  email_subject: 'Contact form submission'
  send_button_text: 'Send Message'

social_settings:
  behance_url: ''
  instagram_url: ''
  facebook_url: ''
  twitter_url: ''
  snapchat_url: ''
  youtube_url: ''
  google-plus_url: ''
  vimeo_url: ''
  pinterest_url: ''
  medium_url: ''
  quora_url: ''
  amazon_url: ''
  apple_url: ''
  android_url: ''
  tumblr_url: ''
  dribbble_url: ''
  deviantart_url: ''
  github_url: 'https://github.com/Lizhen-ZHU'
  reddit_url: ''
  flickr_url: ''
  etsy_url: ''
  kickstarter_url: ''
  soundcloud_url: ''
  spotify_url: ''
  bandcamp_url: ''
  linkedin_url: 'https://wordpress.com/view/digitalfoundations900710997.wordpress.com'


color_settings:
  background_color: '#ffffff'
  background_alt_color: '#f4f5f6'
  text_dark_color: '#2A2F36'
  text_medium_color: '#6C7A89'
  text_light_color: '#ABB7B7'
  accent_color: '#F2784B'
  border_color: '#dddddd'
  overlay_background_color: '#ffffff'
  overlay_text_color: '#2A2F36'
  overlay_accent_color: '#F2784B'
  error_color: '#D64541'

font_settings:
  font_embed: '<link href="https://fonts.googleapis.com/css?family=Muli:300,400,600,700" rel="stylesheet">'
  title_font: '"Muli", sans-serif'
  body_font: '"Muli", sans-serif'
  regular_weight: 300
  bold_weight: 700
  site_title:
    small_size: 25
    medium_size: 30
    large_size: 35
    weight: 700
    letter_spacing: -0.02
  menu:
    small_size: 30
    medium_size: 15
    large_size: 17
    weight: 600
    letter_spacing: 0
  grid_item_title:
    small_size: 22
    medium_size: 30
    large_size: 35
    weight: 700
    letter_spacing: -0.02
  grid_item_subtitle:
    small_size: 15
    medium_size: 17
    large_size: 19
    weight: 400
    letter_spacing: 0
  h1:
    small_size: 25
    medium_size: 35
    large_size: 45
    weight: 700
    letter_spacing: -0.02
    line_height: 1.2
  h2:
    small_size: 22
    medium_size: 30
    large_size: 35
    weight: 700
    letter_spacing: -0.02
    line_height: 1.2
  h3:
    small_size: 22
    medium_size: 25
    large_size: 30
    weight: 700
    letter_spacing: -0.02
    line_height: 1.3
  h4:
    small_size: 17
    medium_size: 22
    large_size: 22
    weight: 700
    letter_spacing: 0
    line_height: 1.6
  h5:
    small_size: 17
    medium_size: 20
    large_size: 20
    weight: 700
    letter_spacing: 0
    line_height: 1.6
  h6:
    small_size: 15
    medium_size: 17
    large_size: 18
    weight: 700
    letter_spacing: 0
    line_height: 1.6
  p:
    small_size: 15
    medium_size: 16
    large_size: 17
    weight: 300
    letter_spacing: 0
    line_height: 1.6
  blockquote:
    small_size: 25
    medium_size: 35
    large_size: 45
    weight: 300
    letter_spacing: -0.02
    line_height: 1.6
  buttons:
    weight: 600
    letter_spacing: 0

advanced_settings:
  analytics_code: ""
  custom_styles: ""
  header_js: ""
  footer_js: ""
